/* Server version: WI-V6.3.4.18393 Firebird 2.1 
SET CLIENTLIB 'fbclient.dll';
   SQLDialect: 3. ODS: 11.1. Forced writes: On. Sweep inteval: 20000.
   Page size: 8192. Cache pages: 2048 (16384 Kb). Read-only: False. */

SET NAMES ISO8859_2;

SET SQL DIALECT 3;

CONNECT 'E:\Projetos\Dorivaldo\DGESTAO\db\BUSINESS_CLIENTE.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

SET AUTODDL ON;

ALTER TABLE TBVENDAS ADD NFE_VALOR_BASE_ICMS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_ICMS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_BASE_ICMS_SUBST DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_ICMS_SUBST DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_PRODUTO DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_FRETE DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_SEGURO DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_DESCONTO DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_II DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_IPI DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_PIS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_COFINS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_OUTROS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_NOTA DMN_MONEY;

