/* Create Domains... */
CREATE DOMAIN DMN_FUNCAOACESSO AS CHAR(2) CHECK(value in('VE','GV','DI','OF','OC','ES','GF','TI'));

COMMENT ON DOMAIN DMN_FUNCAOACESSO IS
'Perfil de Acesso:

VE. Vendedor
GV. GerenteVendas
DI. Diretor
OF. Operador Financeiro
OC. Operador Caixa
ES. Estoquista
GF. Gerente Financeiro
TI. Tecnologiada Informacao';

/* Create Table... */
CREATE TABLE TB_TESTE(CODIGO INTEGER NOT NULL,
NOME VARCHAR(250));


CREATE TABLE TBTPDESPESA(COD SMALLINT NOT NULL,
TIPODESP VARCHAR(25));


CREATE TABLE TBUSERS(NOME VARCHAR(12) NOT NULL,
SENHA VARCHAR(6) NOT NULL,
NOMECOMPLETO DMN_NOME NOT NULL,
FUNCAO DMN_FUNCAOACESSO NOT NULL);


COMMENT ON COLUMN TBUSERS.FUNCAO IS
'Perfil de Acesso:

VE. Vendedor
GV. GerenteVendas
DI. Diretor
OF. Operador Financeiro
OC. Operador Caixa
ES. Estoquista
GF. Gerente Financeiro
TI. Tecnologiada Informacao';


ALTER TABLE TBCONTPAG ADD CODTPDESP SMALLINT;

ALTER TABLE TBEMPRESA ADD TIPO_REGIME_NFE SMALLINT;

COMMENT ON COLUMN TBEMPRESA.TIPO_REGIME_NFE IS
'CRT:

0. Simples Nacional (1)
1. Simples Excesso Receita (2)
2. Regime Normal (3)';

ALTER TABLE TBEMPRESA ADD SERIE_NFE SMALLINT;

ALTER TABLE TBEMPRESA ADD NUMERO_NFE INTEGER;

ALTER TABLE TBEMPRESA ADD LOTE_ANO_NFE SMALLINT;

ALTER TABLE TBEMPRESA ADD LOTE_NUM_NFE INTEGER;

ALTER TABLE TBVENDAS ADD LOTE_NFE_ANO SMALLINT;

ALTER TABLE TBVENDAS ADD LOTE_NFE_NUMERO INTEGER;

ALTER TABLE TBVENDAS ADD NFE_ENVIADA DMN_LOGICO;

ALTER TABLE TBVENDAS ADD CANCEL_USUARIO VARCHAR(50) CHARACTER SET NONE;

ALTER TABLE TBVENDAS ADD CANCEL_DATAHORA TIMESTAMP;

ALTER TABLE TBVENDAS ADD CANCEL_MOTIVO DMN_TEXTO;

ALTER TABLE TBVENDAS ADD XML_NFE_FILENAME VARCHAR(250);

ALTER TABLE TBVENDAS ADD NFE_VALOR_BASE_ICMS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_ICMS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_BASE_ICMS_SUBST DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_ICMS_SUBST DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_PRODUTO DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_FRETE DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_SEGURO DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_DESCONTO DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_II DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_IPI DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_PIS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_COFINS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_OUTROS DMN_MONEY;

ALTER TABLE TBVENDAS ADD NFE_VALOR_TOTAL_NOTA DMN_MONEY;

/* Create Views... */
/* Create view: VW_TIPO_REGIME_NFE (ViwData.CreateDependDef) */
CREATE VIEW VW_TIPO_REGIME_NFE(
CODIGO,
DESCRICAO)
 AS 
Select First 1
    0 as Codigo
  , 'Simples Nacional (1)' as Descricao
from TBORIGEMPROD

union

Select First 1
    1 as Codigo
  , 'Simples Excesso Receita (2)' as Descricao
from TBORIGEMPROD

union

Select First 1
    1 as Codigo
  , 'Regime Normal (3)' as Descricao
from TBORIGEMPROD
;


/* Create generator... */
CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2011;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2012;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2013;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2014;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2015;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2016;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2017;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2018;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2019;

CREATE GENERATOR GEN_NUMERO_LOTE_NFE_2020;

CREATE GENERATOR GEN_TBTPDESPESA_ID;


/* Create Primary Key... */
ALTER TABLE TB_TESTE ADD CONSTRAINT PK_TB_TESTE PRIMARY KEY (CODIGO);

ALTER TABLE TBTPDESPESA ADD CONSTRAINT PK_TBTPDESPESA PRIMARY KEY (COD);

ALTER TABLE TBUSERS ADD CONSTRAINT PK_TBUSERS PRIMARY KEY (NOME);

/* Create Foreign Key... */
RECONNECT;

ALTER TABLE TBCONTPAG ADD CONSTRAINT FK_TBCONTPAG_1 FOREIGN KEY (CODTPDESP) REFERENCES TBTPDESPESA (COD);

/* Create trigger... */
SET TERM ^ ;

CREATE TRIGGER TB_TESTE_CODIGO FOR TB_TESTE
ACTIVE BEFORE INSERT POSITION 0 
As
Begin
  If (New.Codigo Is Null) Then
    New.Codigo = Gen_id(Gen_tb_teste_codigo, 1);
End
^


/* Create Views... */

/* Create(Add) Crant */
SET TERM ; ^

GRANT ALL ON MON$ATTACHMENTS TO PUBLIC;

GRANT ALL ON MON$CALL_STACK TO PUBLIC;

GRANT ALL ON MON$DATABASE TO PUBLIC;

GRANT ALL ON MON$IO_STATS TO PUBLIC;

GRANT ALL ON MON$RECORD_STATS TO PUBLIC;

GRANT ALL ON MON$STATEMENTS TO PUBLIC;

GRANT ALL ON MON$TRANSACTIONS TO PUBLIC;

GRANT ALL ON TB_TESTE TO PUBLIC;

GRANT ALL ON TB_TESTE TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON TBAJUSTESTOQ TO PUBLIC;

GRANT ALL ON TBBAIRRO TO PUBLIC;

GRANT ALL ON TBBANCO TO PUBLIC;

GRANT ALL ON TBCFOP TO PUBLIC;

GRANT ALL ON TBCIDADE TO PUBLIC;

GRANT ALL ON TBCLIENTE TO PUBLIC;

GRANT ALL ON TBCOMPRAS TO PUBLIC;

GRANT ALL ON TBCOMPRASITENS TO PUBLIC;

GRANT ALL ON TBCONDICAOPAGTO TO PUBLIC;

GRANT ALL ON TBCONTPAG TO PUBLIC;

GRANT ALL ON TBCONTPAG_BAIXA TO PUBLIC;

GRANT ALL ON TBCONTREC TO PUBLIC;

GRANT ALL ON TBCONTREC_BAIXA TO PUBLIC;

GRANT ALL ON TBDISTRITO TO PUBLIC;

GRANT ALL ON TBEMPRESA TO PUBLIC;

GRANT ALL ON TBESTADO TO PUBLIC;

GRANT ALL ON TBFORMPAGTO TO PUBLIC;

GRANT ALL ON TBFORNECEDOR TO PUBLIC;

GRANT ALL ON TBFORNECEDOR_GRUPO TO PUBLIC;

GRANT ALL ON TBGRUPOPROD TO PUBLIC;

GRANT ALL ON TBLANCDEPOS TO PUBLIC;

GRANT ALL ON TBLOGRADOURO TO PUBLIC;

GRANT ALL ON TBORIGEMPROD TO PUBLIC;

GRANT ALL ON TBPAIS TO PUBLIC;

GRANT ALL ON TBPEDIDOITENS TO PUBLIC;

GRANT ALL ON TBPEDIDOS TO PUBLIC;

GRANT ALL ON TBPRODHIST TO PUBLIC;

GRANT ALL ON TBPRODUTO TO PUBLIC;

GRANT ALL ON TBSECAOPROD TO PUBLIC;

GRANT ALL ON TBSENHA_AUTORIZACAO TO PUBLIC;

GRANT ALL ON TBTIPO_LOGRADOURO TO PUBLIC;

GRANT ALL ON TBTPDESPESA TO PUBLIC;

GRANT ALL ON TBTPDESPESA TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON TBTRIBUTACAO_TIPO TO PUBLIC;

GRANT ALL ON TBUNIDADEPROD TO PUBLIC;

GRANT ALL ON TBUSERS TO PUBLIC;

GRANT ALL ON TBUSERS TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON TBVENDAS TO PUBLIC;

GRANT ALL ON TBVENDEDOR TO PUBLIC;

GRANT ALL ON TVENDASITENS TO PUBLIC;

GRANT ALL ON VW_CONDICAOPAGTO TO PUBLIC;

GRANT ALL ON VW_ORIGEM_PRODUTO TO PUBLIC;

GRANT ALL ON VW_TIPO_ALIQUOTA TO PUBLIC;

GRANT ALL ON VW_TIPO_REGIME_NFE TO PUBLIC;

GRANT ALL ON VW_TIPO_REGIME_NFE TO SYSDBA WITH GRANT OPTION;

GRANT ALL ON VW_TIPO_TRIBUTACAO TO PUBLIC;

GRANT EXECUTE ON PROCEDURE GET_DIA_UTIL TO PUBLIC;

GRANT EXECUTE ON PROCEDURE SET_DUPLICATA_PAGAR TO PUBLIC;

GRANT EXECUTE ON PROCEDURE SET_GERAR_DUPLICATAS TO PUBLIC;

GRANT EXECUTE ON PROCEDURE SET_GERAR_TITULOS TO PUBLIC;

GRANT EXECUTE ON PROCEDURE SET_TITULO_RECEBER TO PUBLIC;


