Insert Into TBBANCO values ('000', 'BANCO BANKPAR S.A.', 'www.aexp.com');
Insert Into TBBANCO values ('001', 'BANCO DO BRASIL S.A.', 'www.bb.com.br');
Insert Into TBBANCO values ('003', 'BANCO DA AMAZÔNIA S.A.', 'www.bancoamazonia.com.br');
Insert Into TBBANCO values ('004', 'BANCO DO NORDESTE DO BRASIL S.A.', 'www.banconordeste.gov.br');
Insert Into TBBANCO values ('021', 'BANESTES S.A. BANCO DO ESTADO DO ESPÍRITO SANTO', 'www.banestes.com.br');
Insert Into TBBANCO values ('024', 'BANCO DE PERNAMBUCO S.A. - BANDEPE', 'www.bandepe.com.br');
Insert Into TBBANCO values ('025', 'BANCO ALFA S.A.', 'www.bancoalfa.com.br');
Insert Into TBBANCO values ('029', 'BANCO BANERJ S.A.', 'www.banerj.com.br');
Insert Into TBBANCO values ('031', 'BANCO BEG S.A.', 'www.itau.com.br');
Insert Into TBBANCO values ('033', 'BANCO SANTANDER (BRASIL) S.A.', 'www.santander.com.br');
Insert Into TBBANCO values ('036', 'BANCO BRADESCO BBI S.A.', '');
Insert Into TBBANCO values ('037', 'BANCO DO ESTADO DO PARÁ S.A.', 'www.banparanet.com.br');
Insert Into TBBANCO values ('038', 'BANCO BANESTADO S.A.', 'www.banestado.com.br');
Insert Into TBBANCO values ('040', 'BANCO CARGILL S.A.', 'www.bancocargill.com.br');
Insert Into TBBANCO values ('041', 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.', 'www.banrisul.com.br');
Insert Into TBBANCO values ('044', 'BANCO BVA S.A.', 'www.bancobva.com.br');
Insert Into TBBANCO values ('045', 'BANCO OPPORTUNITY S.A.', 'www.opportunity.com.br');
Insert Into TBBANCO values ('047', 'BANCO DO ESTADO DE SERGIPE S.A.', 'www.banese.com.br');
Insert Into TBBANCO values ('062', 'HIPERCARD BANCO MÚLTIPLO S.A.', 'www.hipercard.com.br');
Insert Into TBBANCO values ('063', 'BANCO IBI S.A. BANCO MÚLTIPLO', 'www.ibi.com.br');
Insert Into TBBANCO values ('065', 'BANCO LEMON S.A.', 'www.lemon.com');
Insert Into TBBANCO values ('069', 'BPN BRASIL BANCO MÚLTIPLO S.A.', 'www.bpnbrasil.com.br');
Insert Into TBBANCO values ('070', 'BRB - BANCO DE BRASÍLIA S.A.', 'www.brb.com.br');
Insert Into TBBANCO values ('072', 'BANCO RURAL MAIS S.A.', 'www.rural.com.br');
Insert Into TBBANCO values ('073', 'BB BANCO POPULAR DO BRASIL S.A.', 'www.bancopopulardobrasil.com.br');
Insert Into TBBANCO values ('074', 'BANCO J. SAFRA S.A.', 'www.jsafra.com.br');
Insert Into TBBANCO values ('078', 'BES INVESTIMENTO DO BRASIL S.A.-BANCO DE INVESTIMENTO', 'www.besinvestimento.com.br');
Insert Into TBBANCO values ('096', 'BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A', 'www.bmf.com.br');
Insert Into TBBANCO values ('104', 'CAIXA ECONÔMICA FEDERAL', 'www.caixa.gov.br');
Insert Into TBBANCO values ('107', 'BANCO BBM S.A.', 'www.bbmbank.com.br');
Insert Into TBBANCO values ('151', 'BANCO NOSSA CAIXA S.A.', 'www.nossacaixa.com.br');
Insert Into TBBANCO values ('184', 'BANCO ITAÚ BBA S.A.', 'www.itaubba.com.br');
Insert Into TBBANCO values ('204', 'BANCO BRADESCO CARTÕES S.A.', 'www.iamex.com.br');
Insert Into TBBANCO values ('208', 'BANCO UBS PACTUAL S.A.', 'www.pactual.com.br');
Insert Into TBBANCO values ('214', 'BANCO DIBENS S.A.', 'www.bancodibens.com.br');
Insert Into TBBANCO values ('215', 'BANCO COMERCIAL E DE INVESTIMENTO SUDAMERIS S.A.', 'www.sudameris.com.br');
Insert Into TBBANCO values ('217', 'BANCO JOHN DEERE S.A.', 'www.johndeere.com.br');
Insert Into TBBANCO values ('222', 'BANCO CALYON BRASIL S.A.', 'www.calyon.com.br');
Insert Into TBBANCO values ('224', 'BANCO FIBRA S.A.', 'www.bancofibra.com.br');
Insert Into TBBANCO values ('225', 'BANCO BRASCAN S.A.', 'www.bancobrascan.com.br');
Insert Into TBBANCO values ('229', 'BANCO CRUZEIRO DO SUL S.A.', 'www.bcsul.com.br');
Insert Into TBBANCO values ('230', 'UNICARD BANCO MÚLTIPLO S.A.', 'www.unicard.com.br');
Insert Into TBBANCO values ('233', 'BANCO GE CAPITAL S.A.', 'www.bancoge.com.br');
Insert Into TBBANCO values ('237', 'BANCO BRADESCO S.A.', 'www.bradesco.com.br');
Insert Into TBBANCO values ('246', 'BANCO ABC BRASIL S.A.', 'www.abcbrasil.com.br');
Insert Into TBBANCO values ('248', 'BANCO BOAVISTA INTERATLÂNTICO S.A.', '');
Insert Into TBBANCO values ('249', 'BANCO INVESTCRED UNIBANCO S.A.', '');
Insert Into TBBANCO values ('250', 'BANCO SCHAHIN S.A.', 'www.bancoschahin.com.br');
Insert Into TBBANCO values ('263', 'BANCO CACIQUE S.A.', 'www.bancocacique.com.br');
Insert Into TBBANCO values ('265', 'BANCO FATOR S.A.', 'www.bancofator.com.br');
Insert Into TBBANCO values ('318', 'BANCO BMG S.A.', 'www.bancobmg.com.br');
Insert Into TBBANCO values ('320', 'BANCO INDUSTRIAL E COMERCIAL S.A.', 'www.bicbanco.com.br');
Insert Into TBBANCO values ('341', 'BANCO ITAÚ S.A.', 'www.itau.com.br');
Insert Into TBBANCO values ('356', 'BANCO REAL S.A.', 'www.bancoreal.com.br');
Insert Into TBBANCO values ('366', 'BANCO SOCIÉTÉ GÉNÉRALE BRASIL S.A.', 'www.sgbrasil.com.br');
Insert Into TBBANCO values ('370', 'BANCO WESTLB DO BRASIL S.A.', 'www.westlb.com.br');
Insert Into TBBANCO values ('376', 'BANCO J. P. MORGAN S.A.', 'www.jpmorgan.com');
Insert Into TBBANCO values ('389', 'BANCO MERCANTIL DO BRASIL S.A.', 'www.mercantil.com.br');
Insert Into TBBANCO values ('394', 'BANCO FINASA BMC S.A.', 'www.bmc.com.br');
Insert Into TBBANCO values ('399', 'HSBC BANK BRASIL S.A. - BANCO MÚLTIPLO', 'www.hsbc.com.br');
Insert Into TBBANCO values ('409', 'UNIBANCO - UNIÃO DE BANCOS BRASILEIROS S.A.', 'www.unibanco.com.br');
Insert Into TBBANCO values ('422', 'BANCO SAFRA S.A.', 'www.safra.com.br');
Insert Into TBBANCO values ('453', 'BANCO RURAL S.A.', 'www.rural.com.br');
Insert Into TBBANCO values ('456', 'BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S.A.', 'www.btm.com.br');
Insert Into TBBANCO values ('464', 'BANCO SUMITOMO MITSUI BRASILEIRO S.A.', '');
Insert Into TBBANCO values ('473', 'BANCO CAIXA GERAL - BRASIL S.A.', '');
Insert Into TBBANCO values ('477', 'CITIBANK N.A.', 'www.citibank.com/brasil');
Insert Into TBBANCO values ('479', 'BANCO ITAÚBANK S.A', 'www.itaubank.com.br');
Insert Into TBBANCO values ('487', 'DEUTSCHE BANK S.A. - BANCO ALEMÃO', 'www.deutsche-bank.com.br');
Insert Into TBBANCO values ('488', 'JPMORGAN CHASE BANK', 'www.jpmorganchase.com');
Insert Into TBBANCO values ('492', 'ING BANK N.V.', 'www.ing.com');
Insert Into TBBANCO values ('505', 'BANCO CREDIT SUISSE (BRASIL) S.A.', 'www.csfb.com');
Insert Into TBBANCO values ('600', 'BANCO LUSO BRASILEIRO S.A.', 'www.lusobrasileiro.com.br');
Insert Into TBBANCO values ('604', 'BANCO INDUSTRIAL DO BRASIL S.A.', 'www.bancoindustrial.com.br');
Insert Into TBBANCO values ('610', 'BANCO VR S.A.', 'www.vr.com.br');
Insert Into TBBANCO values ('611', 'BANCO PAULISTA S.A.', 'www.bancopaulista.com.br');
Insert Into TBBANCO values ('612', 'BANCO GUANABARA S.A.', 'www.bcoguan.com.br');
Insert Into TBBANCO values ('623', 'BANCO PANAMERICANO S.A.', 'www.panamericano.com.br');
Insert Into TBBANCO values ('626', 'BANCO FICSA S.A.', 'www.ficsa.com.br');
Insert Into TBBANCO values ('630', 'BANCO INTERCAP S.A.', 'www.intercap.com.br');
Insert Into TBBANCO values ('633', 'BANCO RENDIMENTO S.A.', 'www.rendimento.com.br');
Insert Into TBBANCO values ('634', 'BANCO TRIÂNGULO S.A.', 'www.tribanco.com.br');
Insert Into TBBANCO values ('637', 'BANCO SOFISA S.A.', 'www.sofisa.com.br');
Insert Into TBBANCO values ('638', 'BANCO PROSPER S.A.', 'www.bancoprosper.com.br');
Insert Into TBBANCO values ('641', 'BANCO ALVORADA S.A.', '');
Insert Into TBBANCO values ('643', 'BANCO PINE S.A.', 'www.bancopine.com.br');
Insert Into TBBANCO values ('652', 'ITAÚ UNIBANCO HOLDING S.A.', 'www.itau.com.br');
Insert Into TBBANCO values ('653', 'BANCO INDUSVAL S.A.', 'www.indusval.com.br');
Insert Into TBBANCO values ('655', 'BANCO VOTORANTIM S.A.', 'www.bancovotorantim.com.br');
Insert Into TBBANCO values ('707', 'BANCO DAYCOVAL S.A.', 'www.daycoval.com.br');
Insert Into TBBANCO values ('719', 'BANIF-BANCO INTERNACIONAL DO FUNCHAL (BRASIL)S.A.', 'www.banif.com.br');
Insert Into TBBANCO values ('734', 'BANCO GERDAU S.A.', 'www.bancogerdau.com.br');
Insert Into TBBANCO values ('740', 'BANCO BARCLAYS S.A.', 'www.barclays.com');
Insert Into TBBANCO values ('745', 'BANCO CITIBANK S.A.', 'www.citibank.com.br');
Insert Into TBBANCO values ('746', 'BANCO MODAL S.A.', 'www.bancomodal.com.br');
Insert Into TBBANCO values ('747', 'BANCO RABOBANK INTERNATIONAL BRASIL S.A.', 'www.rabobank.com.br');
Insert Into TBBANCO values ('748', 'BANCO COOPERATIVO SICREDI S.A.', 'www.sicredi.com.br');
Insert Into TBBANCO values ('749', 'BANCO SIMPLES S.A.', 'www.bancosimples.com.br');
Insert Into TBBANCO values ('751', 'DRESDNER BANK BRASIL S.A. - BANCO MÚLTIPLO', 'www.dkib.com.br');
Insert Into TBBANCO values ('752', 'BANCO BNP PARIBAS BRASIL S.A.', 'www.bnpparibas.com.br');
Insert Into TBBANCO values ('755', 'BANCO MERRILL LYNCH DE INVESTIMENTOS S.A.', 'www.ml.com');
Insert Into TBBANCO values ('756', 'BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB', 'www.bancoob.com.br');
Insert Into TBBANCO values ('081-7', 'CONCÓRDIA BANCO S.A.', '');
Insert Into TBBANCO values ('082-5', 'BANCO TOPÁZIO S.A.', '');
Insert Into TBBANCO values ('083-3', 'BANCO DA CHINA BRASIL S.A.', '');
Insert Into TBBANCO values ('M03', 'BANCO FIAT S.A.', 'www.bancofiat.com.br');
Insert Into TBBANCO values ('M06', 'BANCO DE LAGE LANDEN BRASIL S.A.', 'www.delagelanden.com');
Insert Into TBBANCO values ('M07', 'BANCO GMAC S.A.', 'www.bancogm.com.br');
Insert Into TBBANCO values ('M08', 'BANCO CITICARD S.A.', 'www.credicardbanco.com.br');
Insert Into TBBANCO values ('M09', 'BANCO ITAUCRED FINANCIAMENTOS S.A.', 'www.itaucred.com.br');
Insert Into TBBANCO values ('M11', 'BANCO IBM S.A.', 'www.ibm.com/br/financing/');
Insert Into TBBANCO values ('M14', 'BANCO VOLKSWAGEN S.A.', 'www.bancovw.com.br');
Insert Into TBBANCO values ('M16', 'BANCO RODOBENS S.A.', 'www.rodobens.com.br');
Insert Into TBBANCO values ('M18', 'BANCO FORD S.A.', 'www.bancoford.com.br');
Insert Into TBBANCO values ('M19', 'BANCO CNH CAPITAL S.A.', 'www.bancocnh.com.br');
Insert Into TBBANCO values ('M20', 'BANCO TOYOTA DO BRASIL S.A.', 'www.bancotoyota.com.br');
Insert Into TBBANCO values ('M22', 'BANCO HONDA S.A.', 'www.bancohonda.com.br');


