INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (1, 0, 1, NULL, 0, '1000000000', 'ATIVO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (2, 0, 1, NULL, 0, '2000000000', 'PASSIVO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (3, 0, 1, NULL, 0, '3000000000', 'DESPESA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (4, 0, 1, NULL, 0, '4000000000', 'RECEITA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (5, 0, 2, 1, 0, '5000000000', 'RESULTADO DIMINUTIVO DO EXERCICIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (6, 0, 2, 1, 0, '6000000000', 'RESULTADO AUMENTATIVO DO EXERCICIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (7, 0, 2, 2, 0, '2100000000', 'PASSIVO CIRCULANTE', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (8, 0, 2, 2, 0, '2200000000', 'EXIGIVEL A LONGO PRAZO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (9, 0, 2, 2, 0, '2300000000', 'RESULTADO DE EXERCICIO FUTURO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (10, 0, 2, 2, 0, '2400000000', 'PATRIMONIO LIQUIDO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (11, 0, 2, 3, 0, '4100000000', 'RECEITA OPERACIONAL BRUTA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (12, 0, 2, 3, 0, '4200000000', 'DEDUCAO DE RECEITA BRUTA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (13, 0, 2, 3, 0, '4300000000', 'RECEITAS FINANCEIRAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (14, 0, 2, 3, 0, '4400000000', 'OUTRAS RECEITAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (15, 0, 2, 3, 0, '4500000000', 'RECEITAS NAO OPERACIONAIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (16, 0, 2, 4, 0, '3100000000', 'DESPESAS OPERACIONAIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (17, 0, 2, 4, 0, '3200000000', 'PROVISOES P/ IMPOSTOS DE RENDA E CONTRATO SOCIAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (18, 0, 3, 5, 0, '1110000000', 'DISPONIBILIDADE', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (19, 0, 3, 5, 0, '1120000000', 'REALIZAVEIS A CURTO PRAZO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (20, 0, 3, 6, 0, '1210000000', 'IMOBILIZADO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (21, 0, 3, 7, 0, '2110000000', 'EXIGIVEL A CURTO PRAZO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (22, 0, 3, 8, 0, '2210000000', 'EXIBIVEL A LONGO PRAZO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (23, 0, 3, 9, 0, '2310000000', 'RECEITA DE EXERCICIO FUTURO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (24, 0, 3, 10, 0, '2410000000', 'CAPITAL SOCIAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (25, 0, 3, 10, 0, '2420000000', 'RESERVAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (26, 0, 3, 10, 0, '2430000000', 'RESULTADO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (27, 0, 3, 11, 0, '4110000000', 'RECEITA BRUTA VENDAS E SERVICOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (28, 0, 3, 12, 0, '4210000000', 'DEDUCOES E ABATIMENTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (29, 0, 3, 13, 0, '4310000000', 'RECEITAS FINANCEIRAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (30, 0, 3, 14, 0, '4410000000', 'OUTRAS RECEITAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (31, 0, 3, 15, 0, '4510000000', 'RESULTADOS NAO OPERACIONAIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (32, 0, 3, 16, 0, '3110000000', 'DESPESAS ADMINISTRATIVAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (33, 0, 3, 16, 0, '3120000000', 'DESPESAS FINANCEITAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (34, 0, 3, 16, 0, '3130000000', 'DESPESAS TRIBUTARIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (35, 0, 3, 16, 0, '3140000000', 'PROVISOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (36, 0, 3, 17, 0, '3210000000', 'IMPOSTO DE RENDA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (37, 0, 4, 18, 0, '1110100000', 'NUMERICOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (38, 0, 4, 18, 0, '1110200000', 'DEPOSITOS BANCARIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (39, 0, 4, 18, 0, '1110300000', 'APLICACOES FINANCEIRAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (40, 0, 4, 19, 0, '1120100000', 'CLIENTES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (41, 0, 4, 19, 0, '1120200000', 'IMPOSTOS A RECUPERAR', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (42, 0, 4, 19, 0, '1120300000', 'CREDITOS DE FUNCIONARIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (43, 0, 4, 19, 0, '1120400000', 'OUTROS CREDITOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (44, 0, 4, 19, 0, '1120500000', 'DESPESAS ANTECIPADAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (45, 0, 4, 19, 0, '1120600000', 'ESTOQUE', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (46, 0, 4, 20, 0, '1210100000', 'BENS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (47, 0, 4, 20, 0, '1210200000', 'DEPRECIACAO ACUMULADA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (48, 0, 4, 20, 0, '1210300000', 'MARCAS, DIREITOS E PATENTES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (49, 0, 4, 21, 0, '2110100000', 'FORNECEDORES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (50, 0, 4, 21, 0, '2110200000', 'EMPRESTIMOS E FINANCIAMENTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (51, 0, 4, 21, 0, '2110300000', 'OBRIGACOES TRIBUTARIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (52, 0, 4, 21, 0, '2110400000', 'OBRIGACOES TRABALHISTAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (53, 0, 4, 21, 0, '2110500000', 'OUTRAS OBRIGACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (54, 0, 4, 21, 0, '2110600000', 'PROVISOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (55, 0, 4, 22, 0, '2210100000', 'EMPRESTIMOS E FINANCIAMENTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (56, 0, 4, 23, 0, '2310100000', 'RECEITA ANTECIPADA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (57, 0, 4, 24, 0, '2410100000', 'CAPITAL ABERTO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (58, 0, 4, 25, 0, '2420100000', 'RESERVAS DE CAPITAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (59, 0, 4, 25, 0, '2420200000', 'RESERVAS DE LUCROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (60, 0, 4, 26, 0, '2430100000', 'LUCROS E PERDAS ACUMULADOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (61, 0, 4, 27, 0, '4110100000', 'VENDAS DE PRODUTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (62, 0, 4, 27, 0, '4110200000', 'VENDAS DE SERVICOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (63, 0, 4, 28, 0, '4210100000', 'DESCONTOS E ABATIMENTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (64, 0, 4, 28, 0, '4210200000', 'IMPOSTOS S/ VENDAS E SERVICOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (65, 0, 4, 29, 0, '4310100000', 'RECEITAS FINANCEIRAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (66, 0, 4, 30, 0, '4410100000', 'OUTRAS RECEITAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (67, 0, 4, 31, 0, '4510100000', 'GANHOS E PERDAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (68, 0, 4, 32, 0, '3110100000', 'DESPESAS E ENCARGOS SOCIAIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (69, 0, 4, 32, 0, '3110200000', 'OCUPACAO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (70, 0, 4, 32, 0, '3110300000', 'UTILIDADES E SERVICOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (71, 0, 4, 32, 0, '3110400000', 'HONORARIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (72, 0, 4, 32, 0, '3110500000', 'DESPESAS GERAIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (73, 0, 4, 33, 0, '3120100000', 'DESPESAS FINANCEIRAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (74, 0, 4, 34, 0, '3130100000', 'DESPESAS TRIBUTARIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (75, 0, 4, 35, 0, '3140100000', 'PROVISOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (76, 0, 4, 36, 0, '3210100000', 'PROVISAO P/ IMPOSTO DE RENDA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (77, 0, 4, 36, 0, '3210200000', 'PROVISAO DA CONTRIBUICAO SALARIAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (78, 0, 5, 37, 1, '1110100100', 'CAIXA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (79, 0, 5, 38, 1, '1110200100', 'ITAU', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (80, 0, 5, 38, 1, '1110200200', 'BRASIL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (81, 0, 5, 38, 1, '1110200300', 'HSBC', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (82, 0, 5, 38, 1, '1110200400', 'CAIXA ECONOMICA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (83, 0, 5, 38, 1, '1110200500', 'REAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (84, 0, 5, 38, 1, '1110200600', 'BRADESCO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (85, 0, 5, 38, 1, '1110200700', 'BANPARA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (86, 0, 5, 38, 1, '1110200800', 'BANCO RURAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (87, 0, 5, 38, 0, '1110200900', 'CHEQUES A COMPENSAR', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (88, 0, 5, 39, 1, '1110300100', 'ITAU', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (89, 0, 5, 39, 1, '1110300200', 'BRASIL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (90, 0, 5, 39, 1, '1110300300', 'HSBC', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (91, 0, 5, 39, 1, '1110300400', 'CAIXA ECONOMICA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (92, 0, 5, 39, 1, '1110300500', 'REAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (93, 0, 5, 39, 1, '1110300600', 'BRADESCO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (94, 0, 5, 39, 1, '1110300700', 'BANPARA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (95, 0, 5, 39, 1, '1110300800', 'BANCO RURAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (96, 0, 5, 40, 0, '1120100100', 'DUPLICATAS A RECEBER', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (97, 0, 5, 41, 1, '1120200100', 'IRRF A COMPENSAR', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (98, 0, 5, 42, 1, '1120300100', 'ADIANTAMENTO DE SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (99, 0, 5, 42, 1, '1120300200', 'ANTECIPACAO 13 SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (100, 0, 5, 42, 1, '1120300300', 'ADIANTAMENTO DE FERIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (101, 0, 5, 43, 1, '1120400100', 'ADIANTAMENTO DE DESPESAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (102, 0, 5, 43, 1, '1120400200', 'ADIANTAMENTO PARA VIAGEM', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (103, 0, 5, 43, 1, '1120400300', 'CHEQUES EM COBRANCA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (104, 0, 5, 43, 1, '1120400400', 'CONTAS A RECEBER', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (105, 0, 5, 44, 1, '1120500100', 'ENCARGOS FINANCEIROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (106, 0, 5, 44, 1, '1120500200', 'PREMIOS DE SEGURO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (107, 0, 5, 44, 1, '1120500300', 'OUTRAS DESPESAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (108, 0, 5, 45, 1, '1120600100', 'MATERIA-PRIMA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (109, 0, 5, 45, 1, '1120600200', 'MERCADORIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (110, 0, 5, 45, 1, '1120600300', 'PRODUTOS EM FABRICACAO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (111, 0, 5, 45, 1, '1120600400', 'PRODUTOS FINALIZADOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (112, 0, 5, 46, 1, '1210100100', 'BENFEITORIAS EM IMOVEIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (113, 0, 5, 46, 1, '1210100200', 'IMOVEIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (114, 0, 5, 46, 1, '1210100300', 'INSTALACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (115, 0, 5, 46, 1, '1210100400', 'MOVEIS E UTENSILIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (116, 0, 5, 46, 1, '1210100500', 'VEICULOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (117, 0, 5, 47, 1, '1210200100', 'BENFEITORIAS EM IMOVEIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (118, 0, 5, 47, 1, '1210200200', 'IMOVEIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (119, 0, 5, 47, 1, '1210200300', 'INSTALACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (120, 0, 5, 47, 1, '1210200400', 'IMOVEIS E UTENSILIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (121, 0, 5, 47, 1, '1210200500', 'VEICULOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (122, 0, 5, 48, 1, '1210300100', 'LINHAS TELEFONICAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (123, 0, 5, 48, 1, '1210300200', 'MARCAS E PATENTES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (124, 0, 5, 49, 1, '2110100100', 'FORNECEDORES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (125, 0, 5, 49, 1, '2110100200', 'SERVICOS PRESTADOS POR AUTONOMOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (126, 0, 5, 50, 1, '2110200100', 'EMPRESTIMOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (127, 0, 5, 50, 1, '2110200200', 'FINANCIAMENTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (128, 0, 5, 51, 1, '2110300100', 'COFINS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (129, 0, 5, 51, 1, '2110300200', 'CONTRIBUICAO SINDICAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (130, 0, 5, 51, 1, '2110300300', 'IRPJ', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (131, 0, 5, 51, 1, '2110300400', 'IRRF', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (132, 0, 5, 51, 1, '2110300500', 'ISS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (133, 0, 5, 51, 1, '2110300600', 'PIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (134, 0, 5, 52, 1, '2110400100', '13 SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (135, 0, 5, 52, 1, '2110400200', 'CONTRIBUICAO ASSISTENCIAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (136, 0, 5, 52, 1, '2110400300', 'CONTRIBUICAO SINDICAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (137, 0, 5, 52, 1, '2110400400', 'FERIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (138, 0, 5, 52, 1, '2110400500', 'FGTS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (139, 0, 5, 52, 1, '2110400600', 'INSS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (140, 0, 5, 52, 1, '2110400700', 'IRRF', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (141, 0, 5, 52, 1, '2110400800', 'PENSAO ALIMENTICIA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (142, 0, 5, 52, 1, '2110400900', 'P.L.R.', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (143, 0, 5, 52, 1, '2110401000', 'PRO-LABORE', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (144, 0, 5, 52, 1, '2110401100', 'RESCISOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (145, 0, 5, 52, 1, '2110401200', 'SALARIOS E ORDENADOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (146, 0, 5, 53, 1, '2110500100', 'ADIANTAMENTOS DE CLIENTES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (147, 0, 5, 53, 1, '2110500200', 'CONTAS A PAGAR', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (148, 0, 5, 53, 1, '2110500300', 'PREMIOS E SEGUROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (149, 0, 5, 54, 1, '2110600100', '13 SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (150, 0, 5, 54, 1, '2110600200', 'ENCARGOS S/ 13 SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (151, 0, 5, 54, 1, '2110600300', 'FERIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (152, 0, 5, 54, 1, '2110600400', 'ENCARGOS S/ FERIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (153, 0, 5, 55, 1, '2210100100', 'EMPRESTIMOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (154, 0, 5, 55, 1, '2210100200', 'FINANCIAMENTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (155, 0, 5, 56, 1, '2310100100', 'VENDA PARA ENTREGA FUTURA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (156, 0, 5, 57, 1, '2410100100', 'INTEGRALIZADO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (157, 0, 5, 57, 1, '2410100200', 'A INTEGRALIZAR', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (158, 0, 5, 58, 1, '2420100100', 'CORRECAO MONETARIA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (159, 0, 5, 58, 1, '2420100200', 'RESERVA P/ AUMENTO DE CAPITAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (160, 0, 5, 59, 1, '2420200100', 'RESERVA LEGAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (161, 0, 5, 60, 1, '2430100100', 'LUCROS ACUMULADOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (162, 0, 5, 60, 1, '2430100200', 'PERDAS ACUMULADAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (163, 0, 5, 60, 1, '2430100300', 'RESULTADO DO EXERCICIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (164, 0, 5, 61, 1, '4110100100', 'MERCADO LOCAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (165, 0, 5, 61, 1, '4110100200', 'EXPORTACAO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (166, 0, 5, 63, 1, '4210100100', 'DESCONTOS CONCEDIDOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (167, 0, 5, 63, 1, '4210100200', 'DEVOLUCAO DE VENDAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (168, 0, 5, 63, 1, '4210100300', 'VENDAS CANCELADAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (169, 0, 5, 64, 1, '4210200100', 'COFINS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (170, 0, 5, 64, 1, '4210200200', 'P.I.S.', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (171, 0, 5, 65, 1, '4310100100', 'DESCONTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (172, 0, 5, 65, 1, '4310100200', 'JUROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (173, 0, 5, 65, 1, '4310100300', 'RENDIMENTOS DE APLICACOES FINANCEIRAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (174, 0, 5, 65, 1, '4310100400', 'VARIACAO MONETARIA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (175, 0, 5, 65, 1, '4310100500', 'OUTRAS RECUPERACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (176, 0, 5, 66, 1, '4410100100', 'VENDA DE SUCATAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (177, 0, 5, 66, 1, '4410100200', 'RECUPERACOES DIVERSAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (178, 0, 5, 66, 1, '4410100300', 'OUTRAS RECEITAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (179, 0, 5, 67, 1, '4510100100', 'GANHOS E PERDAS NA ALIENACAO DE BENS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (180, 0, 5, 67, 1, '4510100200', 'VALOR LIQUIDO DE BENS BAIXADOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (181, 0, 5, 68, 1, '3110100100', '13 SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (182, 0, 5, 68, 1, '3110100200', 'FERIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (183, 0, 5, 68, 1, '3110100300', 'FGTS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (184, 0, 5, 68, 1, '3110100400', 'HORAS EXTRAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (185, 0, 5, 68, 1, '3110100500', 'INDENIZACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (186, 0, 5, 68, 1, '3110100600', 'INSS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (187, 0, 5, 68, 1, '3110100700', 'PREMIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (188, 0, 5, 68, 1, '3110100800', 'SALARIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (189, 0, 5, 68, 1, '3110100900', 'OUTROS ENCARGOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (190, 0, 5, 69, 1, '3110200100', 'MANUTENCAO E REPAROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (191, 0, 5, 70, 1, '3110300100', 'AGUA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (192, 0, 5, 70, 1, '3110300200', 'CORREIOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (193, 0, 5, 70, 1, '3110300300', 'ENERGIA ELETRICA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (194, 0, 5, 70, 1, '3110300400', 'INTERNET', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (195, 0, 5, 70, 1, '3110300500', 'SEGUROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (196, 0, 5, 70, 1, '3110300600', 'TELEFONE', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (197, 0, 5, 71, 1, '3110400100', 'CONTABEIS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (198, 0, 5, 71, 1, '3110400200', 'DIRETORIA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (199, 0, 5, 72, 1, '3110500100', 'ASSISTENCIA MEDICA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (200, 0, 5, 72, 1, '3110500200', 'CESTA BASICA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (201, 0, 5, 72, 1, '3110500300', 'COMBUSTIVEIS E LUBRIFICANTES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (202, 0, 5, 72, 1, '3110500400', 'COMISSOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (203, 0, 5, 72, 1, '3110500500', 'CONTRIBUICAO SINDICAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (204, 0, 5, 72, 1, '3110500600', 'COPA E COZINHA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (205, 0, 5, 72, 1, '3110500700', 'COPIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (206, 0, 5, 72, 1, '3110500800', 'DEPRECIACOES E AMORTIZACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (207, 0, 5, 72, 1, '3110500900', 'DESPESAS COM CARTORIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (208, 0, 5, 72, 1, '3110501000', 'DESPESAS COM TREINAMENTO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (209, 0, 5, 72, 1, '3110501100', 'DONATIVOS E CONTRIBUICOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (210, 0, 5, 72, 1, '3110501200', 'ESTACIONAMENTO E PEDAGIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (211, 0, 5, 72, 1, '3110501300', 'FERIAS E CONVENCOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (212, 0, 5, 72, 1, '3110501400', 'FRETES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (213, 0, 5, 72, 1, '3110501500', 'IMPRESSOS E MATERIAS DE ESCRITORIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (214, 0, 5, 72, 1, '3110501600', 'LANCHES E REFEICOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (215, 0, 5, 72, 1, '3110501700', 'MANUTENCAO DE MAQUINAS E EQUIPAMENTOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (216, 0, 5, 72, 1, '3110501800', 'MANUTENCAO DE VEICULOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (217, 0, 5, 72, 1, '3110501900', 'MATERIA DE CONSUMO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (218, 0, 5, 72, 1, '3110502000', 'PROPAGANDA E PUBLICIDADE', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (219, 0, 5, 72, 1, '3110502100', 'REVISTAS, JORNAIS E PUBLICACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (220, 0, 5, 72, 1, '3110502200', 'SERVICOS PRESTADOS POR TERCEIROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (221, 0, 5, 72, 1, '3110502300', 'VALE-RECEICAO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (222, 0, 5, 72, 1, '3110502400', 'VALE-TRANSPORTE', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (223, 0, 5, 72, 1, '3110502500', 'VIAGENS E REPRESENTACOES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (224, 0, 5, 73, 1, '3120100100', 'DESCONTOS CONCEDIDOS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (225, 0, 5, 73, 1, '3120100200', 'DESPESAS BANCARIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (226, 0, 5, 73, 1, '3120100300', 'JUROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (227, 0, 5, 73, 1, '3120100400', 'IOF', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (228, 0, 5, 74, 1, '3130100100', 'CONTRIBUICAO SOCIAL', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (229, 0, 5, 74, 1, '3130100200', 'CPMF', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (230, 0, 5, 74, 1, '3130100300', 'IMPOSTOS E TAXAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (231, 0, 5, 74, 1, '3130100400', 'INSS S/ SERVICOS DE TERCEIROS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (232, 0, 5, 74, 1, '3130100500', 'IPTU', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (233, 0, 5, 74, 1, '3130100600', 'IPVA', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (234, 0, 5, 74, 1, '3130100700', 'IRPJ S/ LPRES', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (235, 0, 5, 74, 1, '3130100800', 'ISS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (236, 0, 5, 74, 1, '3130100900', 'MULTAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (237, 0, 5, 75, 1, '3140100100', 'FERIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (238, 0, 5, 75, 1, '3140100200', 'ENCARGOS S/ FERIAS', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (239, 0, 5, 75, 1, '3140100300', '13o. SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (240, 0, 5, 75, 1, '3140100400', 'ENCARGOS S/ 13 SALARIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (241, 0, 5, 76, 1, '3210100100', 'IMPOSTO DE RENDA DO EXERCICIO', 1);
INSERT INTO TBPLANO_CONTA (CODIGO, EXERCICIO, NIVEL, GRUPO, TIPO, CODIGO_CONTABIL, DESCRICAO_RESUMIDA, SITUACAO)
                   VALUES (242, 0, 5, 77, 1, '3210200100', 'CONTRIBUICAO SOCIAL DO EXERCICIO', 1);

COMMIT WORK;
